name: accesories_store_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.3
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
